---
- name: wait for all machines to be ready
  hosts: all
  gather_facts: no

  tasks:
    - name: wait for port 22
      wait_for:
        port: 22
      register: connection
      until: connection is succeeded
      retries: 60

