---
mysql_bind_address: 0.0.0.0
mysql_databases:
  - name: owncloud
mysql_users:
  - name: phpmyadmin
    password: PhPmYaDmIn
    priv: "*.*:ALL"
    host: machine9
  - name: owncloud
    password: OwNcLoUd
    priv: "owncloud.*:ALL"
    host: machine9
