---
firewall_services:
  - name: ssh
  - name: http
  - name: https

postfix_relayhost: "[{{ hostvars['server2']['ansible_default_ipv4']['address'] }}]"
rsyslog_remote: "{{ hostvars['server2']['ansible_default_ipv4']['address'] }}"

mysql_bind_address: 0.0.0.0

httpd_applications:
  - name: example
    location: /example/
    backend_url: "http://localhost:8080/example/"

phpmyadmin_username: root
phpmyadmin_password: "{{ vault_mysql_root_password }}"

tomcat_instances:
  - name: example
    directory: /opt/example
    non_ssl_connector_port: 8080
    ssl_connector_port: 8443
    shutdown_port: 8005
    ajp_port: 8009
