---
language: python

sudo: required
dist: trusty

cache:
  - pip

before_install:
  - pip install --upgrade pip
  - pip install ansible
  - ansible-galaxy install --role-file requirements.yml
  - ansible-playbook --inventory localhost, --connection local playbook.yml --extra-vars "ara_configuration_file=${TRAVIS_BUILD_DIR}/ansible/ansible.cfg"

script:
  - cd terraform
  - ssh-keygen -f id_rsa -N ""
  - terraform init
  - terraform apply -auto-approve -var="do_token=${do_token}" -var="cloudflare_email=${cf_email}" -var="cloudflare_token=${cf_token}"
  - cd ../ansible
  - ansible-galaxy install --role-file requirements.yml
  - ansible-playbook --inventory inventory playbook.yml
  - ara generate html ../ansible-integration

deploy:
  - provider: pages
    repo: robertdebock/ansible-integration
    target-branch: gh-pages
    local-dir: "ansible-integration"
    skip-cleanup: true
    github-token: "${gh_token}"
    keep-history: false
    on:
      branch: master

after_script:
  - cd ../terraform
  - terraform destroy -auto-approve -var="do_token=${do_token}" -var="cloudflare_email=${cf_email}" -var="cloudflare_token=${cf_token}"
