---
language: python

cache:
  - pip

env:
  - terraform_version=0.11.7

before_install:
  - pip install --upgrade pip
  - pip install ansible
  - pip install ara
  - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_"${terraform_version}"_linux_amd64.zip
  - mkdir bin
  - unzip terraform_"${terraform_version}"_linux_amd64.zip -d bin
  - chmod 750 bin/terraform

install:
  - cd terraform ; ssh-keygen -f id_rsa -N ""
  - ../bin/terraform init
  - ../bin/terraform apply -auto-approve -var="do_token=${do_token}" -var="cloudflare_email=${cloudflare_email}" -var="cloudflare_token=${cloudflare_token}"
  - cd ../ansible
  - ansible-galaxy install -r requirements.yml
  - cd ../
  - until ansible -m ping all ; do sleep 3 ; done

script:
  - ansible-playbook ansible/playbook.yml

after_script:
  - cd terraform ; ../bin/terraform destroy -auto-approve -var="do_token=${do_token}" -var="cloudflare_email=${cloudflare_email}" -var="cloudflare_token=${cloudflare_token}"
  - ara generate html report

deploy:
  - provider: pages
    repo: robertdebock/ansible-integration
    target-branch: gh-pages
    skip-cleanup: true
    github-token: "${github_token}"
    keep-history: true
    local-dir: report
    on:
      branch: master
