---
language: python

sudo: required
dist: trusty

cache:
  - pip

before_install:
  - pip install --upgrade pip
  - pip install ansible
  - ansible-galaxy install -r requirements.yml
  - ansible-playbook -i localhost, -c local before_install.yml

install:
  - cd terraform
  - ssh-keygen -f id_rsa -N ""
  - terraform init
  - terraform apply -auto-approve -var="do_token=${do_token}" -var="cloudflare_email=${cloudflare_email}" -var="cloudflare_token=${cloudflare_token}"
  - cd ../ansible
  - ansible --version
  - cat /etc/ansible/ansible.cfg
  - ansible-galaxy install -r mail-requirements.yml
  - ansible-galaxy install -r infrastructure-requirements.yml
  - ansible-galaxy install -r webapp-requirements.yml
  - ansible-playbook -i inventory wait.yml

script:
  - ansible-playbook -i inventory mail.yml
  - ansible-playbook -i inventory infrastructure.yml
  - ansible-playbook -i inventory webapp.yml
  - cd ../terraform
  - terraform destroy -auto-approve -var="do_token=${do_token}" -var="cloudflare_email=${cloudflare_email}" -var="cloudflare_token=${cloudflare_token}"
  - cd ../ansible
  - ara generate html ../ansible-integration
  - cd ../

deploy:
  - provider: pages
    repo: robertdebock/ansible-integration
    target-branch: gh-pages
    local-dir: "ansible-integration"
    skip-cleanup: true
    github-token: "${github_token}"
    keep-history: false
    on:
      branch: master
