---
- name: before install
  hosts: localhost
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
      bootstrap_user: root
    - role: robertdebock.ara

  tasks:
    - name: configure ansible (host_key_checking)
      ini_file:
        path: /etc/ansible/ansible.cfg
        section: defaults
        option: host_key_checking
        value: False


    - name: configure ansible (inventory)
      ini_file:
        path: /etc/ansible/ansible.cfg
        section: defaults
        option: inventory
        value: inventory
