---
- name: before install as root
  hosts: localhost
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
      bootstrap_user: root
    - role: robertdebock.terraform
    - role: robertdebock.buildtools
    - role: robertdebock.ara

  tasks:
    - name: configure ansible (host_key_checking)
      ini_file:
        path: ansible/ansible.cfg
        section: defaults
        option: host_key_checking
        value: False
