---
- src: https://github.com/robertdebock/ansible-role-bootstrap.git
  name: robertdebock.bootstrap
- src: https://github.com/robertdebock/ansible-role-buildtools.git
  name: robertdebock.buildtools
- src: https://github.com/robertdebock/ansible-role-clamav.git
  name: robertdebock.clamav
- src: https://github.com/robertdebock/ansible-role-dns.git
  name: robertdebock.dns
- src: https://github.com/robertdebock/ansible-role-digitalocean-agent.git
  name: robertdebock.digitalocean-agent
- src: https://github.com/robertdebock/ansible-role-epel.git
  name: robertdebock.epel
- src: https://github.com/robertdebock/ansible-role-fail2ban.git
  name: robertdebock.fail2ban
- src: https://github.com/robertdebock/ansible-role-haveged.git
  name: robertdebock.haveged
- src: https://github.com/robertdebock/ansible-role-httpd.git
  name: robertdebock.httpd
- src: https://github.com/robertdebock/ansible-role-java.git
  name: robertdebock.java
- src: https://github.com/robertdebock/ansible-role-mysql.git
  name: robertdebock.mysql
- src: https://github.com/robertdebock/ansible-role-php.git
  name: robertdebock.php
- src: https://github.com/robertdebock/ansible-role-postfix.git
  name: robertdebock.postfix
- src: https://github.com/robertdebock/ansible-role-python-pip.git
  name: robertdebock.python-pip
- src: https://github.com/robertdebock/ansible-role-roundcubemail.git
  name: robertdebock.roundcubemail
- src: https://github.com/robertdebock/ansible-role-rsyslog.git
  name: robertdebock.rsyslog
- src: https://github.com/robertdebock/ansible-role-rundeck.git
  name: robertdebock.rundeck
- src: https://github.com/robertdebock/ansible-role-scl.git
  name: robertdebock.scl
- src: https://github.com/robertdebock/ansible-role-spamassassin.git
  name: robertdebock.spamassassin
- src: https://github.com/robertdebock/ansible-role-tomcat.git
  name: robertdebock.tomcat
- src: https://github.com/robertdebock/ansible-role-update.git
  name: robertdebock.update
- src: https://github.com/robertdebock/ansible-role-zabbix.git
  name: robertdebock.zabbix
