---
- name: configure shared items for all machines.
  hosts: machine4.meinit.nl:machine5.meinit.nl
  become: yes
  any_errors_fatal: true

  tasks:
    - name: rsyslog
      include_role:
        name: robertdebock.rsyslog

    - name: ntp
      include_role:
        name: robertdebock.ntp
