---
- name: configure shared items for all machines.
  hosts: machine1.meinit.nl:machine2.meinit.nl:machine3.meinit.nl
  become: yes
  gather_facts: no
  any_errors_fatal: true

  tasks:
    - name: bootstrap
      include_role:
        name: robertdebock.bootstrap

    - name: digitalocean_agent
      include_role:
        name: robertdebock.digitalocean_agent

    - name: create linux groups
      group:
        name: "{{ item.group }}"
      with_items: "{{ linux_users }}"

    - name: create linux users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        comment: "{{ item.comment }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: allow wheel to use sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel\s'
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"

    - name: postfix
      include_role:
        name: robertdebock.postfix
