---
- name: configure shared items for all machines.
  hosts: all:!localhost
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.digitalocean_agent
    - role: robertdebock.common
    - role: robertdebock.firewall
    - role: robertdebock.update
    - role: robertdebock.ntp
    - role: robertdebock.epel
    - role: robertdebock.fail2ban
    - role: robertdebock.postfix
    - role: robertdebock.rsyslog
    - role: robertdebock.users

- hosts: services
  become: yes
  gather_facts: no

  vars_files:
    - vars/vault.yml

  roles:
    - role: robertdebock.spamassassin
    - role: robertdebock.clamav
    - role: robertdebock.dovecot

- hosts: webappservers
  become: yes
  gather_facts: no

  vars_files:
    - vars/vault.yml

  roles:
    - role: robertdebock.mysql
    - role: robertdebock.python_pip
    - role: robertdebock.httpd
    - role: robertdebock.phpmyadmin
    - role: robertdebock.java
    - role: robertdebock.tomcat
