---
- name: configure shared items for all machines.
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: bootstrap
      include_role:
        name: robertdebock.bootstrap

    - name: create linux users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        comment: "{{ item.comment }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: allow wheel to use sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel\s'
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"

    - name: digitalocean-agent
      include_role:
        name: robertdebock.digitalocean-agent

    - name: epel
      include_role:
        name: robertdebock.epel

    - name: rsyslog
      include_role:
        name: robertdebock.rsyslog

    - name: postfix
      include_role:
        name: robertdebock.postfix

    - name: fail2ban
      include_role:
        name: robertdebock.fail2ban

    - name: ntp
      include_role:
        name: robertdebock.ntp

- name: configure shared items for backendservers and webservers
  hosts: backendservers:webservers
  become: yes

  tasks:
    - name: buildtools
      include_role:
        name: robertdebock.buildtools

    - name: scl
      include_role:
        name: robertdebock.scl

    - name: python-pip
      include_role:
        name: robertdebock.python-pip

- name: update all servers
  hosts: all

  tasks:
    - name: update
      include_role:
        name: robertdebock.update

- name: configure database server
  hosts: databaseservers
  become: yes

  tasks:
    - name: mysql
      include_role:
        name: robertdebock.mysql

    - name: create database
      mysql_db:
        name: "{{ item.name }}"
      with_items: "{{ mysql_databases }}"
      loop_control:
        label: "{{ item.name }}"


    - name: create mysql users
      mysql_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        priv: "{{ item.priv }}"
        host: "{{ item.host }}"
      with_items: "{{ mysql_users }}"

- name: configure backendservers
  hosts: backendservers
  become: yes

  tasks:
    - name: dns
      include_role:
        name: robertdebock.dns

    - name: clamav
      include_role:
        name: robertdebock.clamav

    - name: spamassassin
      include_role:
        name: robertdebock.spamassassin

    - name: mysql
      include_role:
        name: robertdebock.mysql

    - name: php
      include_role:
        name: robertdebock.php

    - name: httpd
      include_role:
        name: robertdebock.httpd

    - name: roundcubemail
      include_role:
        name: robertdebock.roundcubemail

    - name: java
      include_role:
        name: robertdebock.java

    - name: rundeck
      include_role:
        name: robertdebock.rundeck

    - name: phpmyadmin
      include_role:
        name: robertdebock.phpmyadmin
      
- name: configure application servers
  hosts: applicationservers
  become: yes

  tasks:
    - name: java
      include_role:
        name: robertdebock.java

    - name: haveged
      include_role:
        name: robertdebock.haveged

    - name: tomcat
      include_role:
        name: robertdebock.tomcat

- name: configure webservers
  hosts: webservers
  become: yes

  tasks:
    - name: httpd
      include_role:
        name: robertdebock.httpd

- name: configure zabbix on all machines
  hosts: all
  become: yes

  tasks:
    - name: zabbix
      include_role:
        name: robertdebock.zabbix
