---
- name: configure shared items for all machines.
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: bootstrap
      include_role:
        name: robertdebock.bootstrap

    - name: create linux users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        comment: "{{ item.comment }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: allow wheel to use sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel\s'
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"

    - name: digitalocean-agent
      include_role:
        name: robertdebock.digitalocean-agent

    - name: postfix
      include_role:
        name: robertdebock.postfix

- name: configure backendservers
  hosts: backendservers
  become: yes

  tasks:
    - name: clamav
      include_role:
        name: robertdebock.clamav

    - name: spamassassin
      include_role:
        name: robertdebock.spamassassin

    - name: php
      include_role:
        name: robertdebock.php

    - name: httpd
      include_role:
        name: robertdebock.httpd

    - name: roundcubemail
      include_role:
        name: robertdebock.roundcubemail

    - name: allow web traffic
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
      with_items:
        - http
        - https

    - name: allow email traffic
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
      with_items:
        - smtp
        - pop3
        - imap

