---
- name: configure shared items for all machines.
  hosts: all:!localhost
  become: yes
  gather_facts: no

  roles:
    - robertdebock.bootstrap
    - robertdebock.digitalocean_agent
    - robertdebock.common
    - robertdebock.firewall
    - robertdebock.update
    - robertdebock.cron
    - robertdebock.ntp
    - robertdebock.epel
    - robertdebock.fail2ban
    - robertdebock.hostname
    - robertdebock.postfix
    - robertdebock.rsyslog
    - robertdebock.users
