---
- name: configure shared items for all machines.
  hosts: server1.meinit.nl:server2.meinit.nl
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.digitalocean_agent
    - role: robertdebock.common
    - role: robertdebock.firewall
    - role: robertdebock.update
    - role: robertdebock.cron
    - role: robertdebock.ntp
    - role: robertdebock.epel
    - role: robertdebock.fail2ban
    - role: robertdebock.hostname
    - role: robertdebock.postfix
    - role: robertdebock.rsyslog
    - role: robertdebock.users
