---
- name: configure shared items for all machines.
  hosts: machine8.meinit.nl
  become: yes
  gather_facts: no

  tasks:
    - name: bootstrap
      include_role:
        name: robertdebock.bootstrap

    - name: digitalocean-agent
      include_role:
        name: robertdebock.digitalocean-agent

    - name: create linux users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        comment: "{{ item.comment }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: allow wheel to use sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel\s'
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"

    - name: java
      include_role:
        name: robertdebock.java

    - name: rundeck
      include_role:
        name: robertdebock.rundeck

    - name: epel
      include_role:
        name: robertdebock.epel

    - name: buildtools
      include_role:
        name: robertdebock.buildtools

    - name: scl
      include_role:
        name: robertdebock.scl

    - name: python-pip
      include_role:
        name: robertdebock.python-pip

    - name: httpd
      include_role:
        name: robertdebock.httpd

    - name: php
      include_role:
        name: robertdebock.php

    - name: mysql
      include_role:
        name: robertdebock.mysql

    - name: phpmyadmin
      include_role:
        name: robertdebock.phpmyadmin
