---
- name: configure items for database machines.
  hosts: machine8.meinit.nl
  become: yes
  any_errors_fatal: true

  roles:
    - role: robertdebock.mysql

- name: configure items for frontend machines.
  hosts: machine9.meinit.nl
  become: yes
  any_errors_fatal: true

  roles:
    - role: robertdebock.java
    - role: robertdebock.rundeck
    - role: robertdebock.epel
    - role: robertdebock.python_pip
    - role: robertdebock.httpd
    - role: robertdebock.php
    - role: robertdebock.phpmyadmin
    - role: robertdebock.owncloud
