---
- hosts: server2.meinit.nl
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.mysql
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
    - role: robertdebock.openssl
    - role: robertdebock.httpd
    - role: robertdebock.phpmyadmin
    - role: robertdebock.java
    - role: robertdebock.tomcat
