---
- name: configure items for application servers.
  hosts: machine6.meinit.nl
  become: yes
  any_errors_fatal: true

  roles:
    - role: robertdebock.java
    - role: robertdebock.tomcat

- name: configure items for web servers.
  hosts: machine7.meinit.nl
  become: yes
  any_errors_fatal: true

  roles:
    - role: robertdebock.epel
    - role: robertdebock.python_pip
    - role: robertdebock.httpd
