---
- name: configure shared items for all machines.
  hosts: machine6.meinit.nl:machine7.meinit.nl
  become: yes
  any_errors_fatal: true

  tasks:
    - name: digitalocean_agent
      include_role:
        name: robertdebock.digitalocean_agent

    - name: create linux groups
      group:
        name: "{{ item.groups }}"
      with_items: "{{ linux_users }}"

    - name: create linux users
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        comment: "{{ item.comment }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Set authorized key took from file
      authorized_key:
        user: "{{ item.name }}"
        key: "{{ item.key }}"
      with_items: "{{ linux_users }}"
      loop_control:
        label: "{{ item.name }}"

    - name: allow wheel to use sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel\s'
        line: "%wheel ALL=(ALL) NOPASSWD: ALL"

- name: configure items for application servers.
  hosts: machine6.meinit.nl
  become: yes
  gather_facts: yes
  any_errors_fatal: true

  tasks:
    - name: java
      include_role:
        name: robertdebock.java

    - name: tomcat
      include_role:
        name: robertdebock.tomcat

- name: configure items for web servers.
  hosts: machine7.meinit.nl
  become: yes
  gather_facts: yes
  any_errors_fatal: true

  tasks:
    - name: epel
      include_role:
        name: robertdebock.epel

    - name: python_pip
      include_role:
        name: robertdebock.python_pip

    - name: httpd
      include_role:
        name: robertdebock.httpd
